apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
  namespace: wap-admin
spec:
  replicas: 4
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: gcr.io/google-samples/whack-a-pod/api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: game
  namespace: wap-admin
spec:
  selector:
    app: game
  ports:
  - port: 8080
    targetPort: 8080