apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wap
  namespace: wap-admin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: wap.statkart.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: game
            port:
              number: 8080
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8080
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: admin
            port:
              number: 8080